import { agentGraph } from "@/lib/agent/graph";
import { HumanMessage, AIMessage } from "@langchain/core/messages";

export async function POST(req: Request) {
  try {
    const body = await req.json();
    console.log("[DEBUG] Raw Request Body:", JSON.stringify(body, null, 2));
    
    const { messages } = body; 

    if (!messages || !Array.isArray(messages) || messages.length === 0) {
      return new Response(JSON.stringify({ error: "Invalid or empty messages array." }), { status: 400 });
    }

    // Limit context window to the last 40 Q&A pairs (80 messages)
    const MAX_MESSAGES = 80;
    const truncatedMessages = messages.slice(-MAX_MESSAGES);

    // Convert UI messages to LangChain Message format
    const langChainMessages = truncatedMessages.map((msg: any) => {
      if (msg.role === 'assistant' || msg.role === 'model') {
        return new AIMessage(msg.content);
      }
      return new HumanMessage(msg.content);
    });

    const stream = new ReadableStream({
      async start(controller) {
        try {
          const events = await agentGraph.streamEvents(
            { messages: langChainMessages },
            { version: "v2" }
          );

          for await (const event of events) {
            const eventType = event.event;
            
            // We only stream text chunks generated by the agent model node directly
            if (eventType === "on_chat_model_stream" && event.name !== "search_mental_health_guidelines") {
              const chunkText = event.data?.chunk?.content;
              if (chunkText && typeof chunkText === "string") {
                controller.enqueue(new TextEncoder().encode(chunkText));
              }
            }
          }
          controller.close();
        } catch (streamError: any) {
          console.error("[DEBUG] Streaming error encountered:", streamError);
          controller.error(streamError);
        }
      }
    });

    return new Response(stream, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'no-cache, no-transform',
        'Connection': 'keep-alive'
      }
    });
  } catch (error: any) {
    console.error("[DEBUG] Full Error Object from LangGraph API:", JSON.stringify(error, Object.getOwnPropertyNames(error), 2));
    
    const errString = String(error?.message || "") + JSON.stringify(error || {});
    
    if (error?.status === 429 || error?.code === 429 || errString.includes("429")) {
      return new Response(JSON.stringify({ 
        error: "Google AI rate limit reached (429 Too Many Requests). The AI is currently taking a quick nap! 🐶💤 Please wait about 1 minute and try again!" 
      }), { status: 429 });
    }

    return new Response(JSON.stringify({ error: "Connection to AI failed. Please try again later." }), { status: 500 });
  }
}
